Добавляет наставника
htmlacademy-htmlcss/825295-sedona-36 pull request #1
Opened 2023-01-17 13:03 UTC by aleksaandr

2023-01-17 13:51 UTC, Dima-Dim requested changes

2023-01-17 13:51 UTC, Dima-Dim commented on Readme.md
> +* Наставник: `Дмитрий Гуляев`.
Привет! Отредактируй, пожалуйста, строку Наставник чтобы было по аналогии со строкой Студент. Для этого нужно добавить ссылку на мой профиль https://htmlacademy.ru/profile/dima

2023-01-18 01:24 UTC, aleksaandr commented on Readme.md
> +* Наставник: `Дмитрий Гуляев`.
Здравствуйте! Добавил.

2023-01-18 02:23 UTC, aleksaandr commented on Readme.md
> +* Наставник: `Дмитрий Гуляев`.
Отправил домашнее задание на проверку повторно.

2023-01-19 05:01 UTC, merged