Внес правки
htmlacademy-htmlcss/825295-sedona-36 pull request #3
Opened 2023-01-23 08:42 UTC by aleksaandr

2023-01-27 05:40 UTC, Dima-Dim requested changes
index-background.jpg что то там и декоративный элемент и бекграйнд белый. Зачем это всё в одном файле?

2023-01-27 05:40 UTC, Dima-Dim commented on catalog.html
> +            <img src="images/header/search.svg" width="20" height="20" alt="Поиск">
https://up.htmlacademy.ru/htmlcss/36/module/2/item/19

2023-01-27 05:40 UTC, Dima-Dim commented on catalog.html
> +              Регистрация
Что за регистрация?

2023-01-27 05:40 UTC, Dima-Dim commented on catalog.html
> +                <img src="images/breadcumbs/to-index-icon.svg" width="12" height="12" alt="На главную">
А вот тут всё было хорошо, не нужно было ничего менять.

2023-01-27 05:40 UTC, Dima-Dim commented on catalog.html
> +          <img src="images/catalog-cards-header/modal-window.svg" width="16" height="14" alt="Модальное окно">
Тоже нет, всё это декоративные изображения, не рассказывающие о том, что это на самом деле. Более того, судя по макету это ещё и элементы, с которыми можно взаимодействовать.

2023-01-27 05:40 UTC, Dima-Dim commented on catalog.html
> +              <img class="card-img" src="images/catalog-cards-list/hotel-1.jpg" width="300" height="212" alt="Гостиница Amara Resort & Spa">
Вот тут да, контентное изображение.

2023-01-27 09:59 UTC, aleksaandr commented on catalog.html
> +            <img src="images/header/search.svg" width="20" height="20" alt="Поиск">
Спасибо, разобрался

2023-01-30 13:18 UTC, Dima-Dim requested changes

2023-01-30 13:18 UTC, Dima-Dim commented on catalog.html
> +              <img src="images/breadcumbs/arrow-icon.svg" width="6" height="10" alt="Текущая страница">
А это чего оставил?

2023-01-30 13:18 UTC, Dima-Dim commented on catalog.html
> +          <span class="visuaaly-hidden">Модальное окно номер 1</span>
Это интерактивные элементы и названия вида `Модальное окно номер 1` не имеют смысла, потому что не делают более понятным то, что здесь происходит.

2023-01-30 13:18 UTC, Dima-Dim commented on index.html
> +            <img src="images/header/heart.svg" width="18" height="17" alt="В избранное">
Тоже не понятно зачем осталось.

2023-01-30 13:18 UTC, Dima-Dim commented on index.html
> +            <div class="house-image">
https://up.htmlacademy.ru/htmlcss/36/criteries#HTML-06

2023-01-30 13:18 UTC, Dima-Dim commented on index.html
> +            <span class="subscription-label">Подписаться</span>
https://up.htmlacademy.ru/htmlcss/36/criteries#HTML-06

2023-01-30 13:18 UTC, Dima-Dim commented on index.html
> +        <div class="searching-button">
Не однозначно, для чего тут этот div.

2023-01-31 18:07 UTC, aleksaandr commented on catalog.html
> +              <img src="images/breadcumbs/arrow-icon.svg" width="6" height="10" alt="Текущая страница">
Убрал, вставил через css

2023-02-01 07:46 UTC, aleksaandr commented on index.html
> +            <img src="images/header/heart.svg" width="18" height="17" alt="В избранное">
Убрал, вставил через css

2023-02-01 07:51 UTC, aleksaandr commented on index.html
> +            <div class="house-image">
Обертку убрал, вставил через css как псевдоэлемент

2023-02-01 08:26 UTC, aleksaandr commented on catalog.html
> +          <span class="visuaaly-hidden">Модальное окно номер 1</span>
Вставил через css, названия поменял

2023-02-01 08:34 UTC, aleksaandr commented on index.html
> +            <span class="subscription-label">Подписаться</span>
Исправил

2023-02-01 08:42 UTC, aleksaandr commented on index.html
> +        <div class="searching-button">
> Не однозначно, для чего тут этот div.

Div убрал. Стили применил на ссылку, но не получилось также как на макете. Может этот коричневый фон экспортировать как картинку svg, подключить через css и потом налепить на нее текст?

2023-02-01 14:08 UTC, Dima-Dim commented on index.html
> +        <div class="searching-button">
Ну нет :) фон кнопки это конечно же просто цвет фона. На этапе базовой стилизации можно это пока оставить так и вернуться к этому позже.

2023-02-01 14:11 UTC, merged

2023-02-01 15:14 UTC, aleksaandr commented on index.html
> +        <div class="searching-button">
Понял, хорошо