Микросетки
htmlacademy-htmlcss/825295-sedona-36 pull request #5
Opened 2023-02-11 09:25 UTC by aleksaandr

2023-02-14 05:27 UTC, Dima-Dim requested changes

2023-02-14 05:27 UTC, Dima-Dim commented on catalog.html
> +                  <button class="catalog-cards-button catalog-cards-button-in-favorites" type="button">
В опубликованной версии https://htmlacademy-htmlcss.github.io/825295-sedona-36/5/catalog.html текст получился с переносом.

2023-02-14 05:27 UTC, Dima-Dim commented on index.html
> +            <li class="advantages-item-image">
Это не отдельный пункт списка, это изображение от следующего пункта.

2023-02-14 05:27 UTC, Dima-Dim commented on index.html
> +              <img src="images/advantages/advantages-photo-2.jpg" width="800" height="385" alt="Гранд Каньон">
Изображения явно не то, оно с каким-то эффектом, а должно быть без, так же как и первое, в этом списке.

2023-02-14 05:27 UTC, Dima-Dim commented on index.html
> +            <li class="advantages-item-image">
Тоже не отдельный пункт, а продолжение первого.

2023-02-14 05:27 UTC, Dima-Dim commented on styles/styles.css
> +button {
https://up.htmlacademy.ru/htmlcss/36/criteries#CSS-02

2023-02-14 05:27 UTC, Dima-Dim commented on styles/styles.css
> +.advantages-item-blue .advantages-description {
:) даже необходимость переименовать `-white` в `-blue` не дала понять что использовать в названиях классов то, как они выглядят не удобно?

2023-02-14 05:27 UTC, Dima-Dim commented on styles/styles.css
> +  height: auto
А без явного указания значения `auto` оно как-то иначе работает?

2023-02-14 09:49 UTC, aleksaandr commented on catalog.html
> +                  <button class="catalog-cards-button catalog-cards-button-in-favorites" type="button">
Видимо я сделал эту кнопку после опубликования, в новом коммите должно быть норм

2023-02-14 10:08 UTC, aleksaandr commented on index.html
> +              <img src="images/advantages/advantages-photo-2.jpg" width="800" height="385" alt="Гранд Каньон">
Исправил

2023-02-14 10:10 UTC, aleksaandr commented on styles/styles.css
> +button {
Убрал. Тогда каждой кнопке прописываю cursor: pointer ?

2023-02-14 10:37 UTC, aleksaandr commented on styles/styles.css
> +  height: auto
В данном случае работает также. Но мне кажется, что стоит оставить у высоты auto и добавить min-width, чтобы размер иконки подстраивался под контент, который в будущем, возможно, будет добавлен в этот блок.

2023-02-14 10:54 UTC, aleksaandr commented on index.html
> +            <li class="advantages-item-image">
Исправил

2023-02-14 10:54 UTC, aleksaandr commented on index.html
> +            <li class="advantages-item-image">
Исправил

2023-02-14 11:13 UTC, aleksaandr commented on styles/styles.css
> +.advantages-item-blue .advantages-description {
У меня нет идей, как более удобно переименовать классы в данном случае. Можно использовать в названиях классов контент, который находится в блоке (например, вместо advantages-item-blue - advantages-item-city), но это не упростит написание кода, как мне кажется. Можно обойтись без дополнительных классов и использовать псевдоклассы, но если добавится новый контент, то все сломается. Как здесь можно сделать более удобно?

2023-02-14 15:01 UTC, Dima-Dim commented on styles/styles.css
> +button {
Вообще у кнопок он должен быть по умолчанию, но если нет, то прописывай там где нужно.

2023-02-14 15:02 UTC, Dima-Dim commented on styles/styles.css
> +.advantages-item-blue .advantages-description {
advantages-item-city уже гораздо лучше, это говорит о том, что стилизует класс, а не как он это делает.

2023-02-14 15:04 UTC, Dima-Dim commented on styles/styles.css
> +  height: auto
Иконка имеет фиксированные размеры, это не текст, который может меняться. А по поводу кода без которого всё работает так же, код нужно писать, если без него не работает или работает не так как нужно.

2023-02-15 02:15 UTC, aleksaandr commented on styles/styles.css
> +button {
Прописал

2023-02-15 02:17 UTC, aleksaandr commented on styles/styles.css
> +  height: auto
Понял, исправил

2023-02-15 02:23 UTC, aleksaandr commented on styles/styles.css
> +.advantages-item-blue .advantages-description {
Исправил

2023-02-15 04:17 UTC, merged