Декоративные элементы
htmlacademy-htmlcss/825295-sedona-36 pull request #7
Opened 2023-02-22 13:16 UTC by aleksaandr

2023-02-26 12:43 UTC, Dima-Dim requested changes
[images/header/figure.svg](https://github.com/htmlacademy-htmlcss/825295-sedona-36/pull/7/files#diff-a8221bbd07ca9454b46f08b62d0acbb9e22207b003174ac86382ecb5d2b16fa8) - а если нужно будет отобразить другую цифру, то как это могло бы работать?

2023-02-26 12:43 UTC, Dima-Dim commented on styles/styles.css
> +  left: 23.8px;
Точности до целых должно быть достаточно.

2023-02-27 03:43 UTC, aleksaandr commented
> [images/header/figure.svg](https://github.com/htmlacademy-htmlcss/825295-sedona-36/pull/7/files#diff-a8221bbd07ca9454b46f08b62d0acbb9e22207b003174ac86382ecb5d2b16fa8) - а если нужно будет отобразить другую цифру, то как это могло бы работать?

 Это через java script будет работать, как счетчик. Получается, надо только зеленый круг вставить как иконку, а цифру через span?

2023-02-27 03:44 UTC, aleksaandr commented on styles/styles.css
> +  left: 23.8px;
Исправил

2023-02-27 03:53 UTC, aleksaandr commented on styles/styles.css
> +  left: 23.8px;
А почему, кстати, нельзя дробные числа здесь?

2023-02-27 09:54 UTC, Dima-Dim commented on styles/styles.css
> +  left: 23.8px;
Можно, но не нужно. Не факт что в мониторах это точно в реальные пиксели попадать будет и станет только хуже.

2023-02-27 09:54 UTC, Dima-Dim commented
> > [images/header/figure.svg](https://github.com/htmlacademy-htmlcss/825295-sedona-36/pull/7/files#diff-a8221bbd07ca9454b46f08b62d0acbb9e22207b003174ac86382ecb5d2b16fa8) - а если нужно будет отобразить другую цифру, то как это могло бы работать?
> 
> Это через java script будет работать, как счетчик. Получается, надо только зеленый круг вставить как иконку, а цифру через span?

Да, цифра должна быть цифрой, а не изображением.

2023-02-27 11:35 UTC, aleksaandr commented on styles/styles.css
> +  left: 23.8px;
Понял, спасибо

2023-02-27 15:10 UTC, Dima-Dim commented on index.html
> +            <span class="tooltip"></span>
https://up.htmlacademy.ru/htmlcss/36/criteries#HTML-06

2023-02-27 15:10 UTC, Dima-Dim commented on styles/styles.css
> +  left: calc(50% - 11px/2 + 7.5px);
Опять какие-то дробные числа.

2023-02-27 15:12 UTC, merged

2023-02-28 07:27 UTC, aleksaandr commented on styles/styles.css
> +  left: calc(50% - 11px/2 + 7.5px);
> Опять какие-то дробные числа.

Исправил

2023-03-01 13:15 UTC, aleksaandr commented on index.html
> +            <span class="tooltip"></span>
> https://up.htmlacademy.ru/htmlcss/36/criteries#HTML-06

А как здесь сделать без span? Я попробовал вместо span ::after, но с ним не работает :hover и текст не появляется при наведении на иконку.

2023-03-02 06:30 UTC, Dima-Dim commented on index.html
> +            <span class="tooltip"></span>
Дело не в самом span-е, а в том, что он пустой. В пустом спане нет смысла в разметке.

2023-03-02 08:42 UTC, aleksaandr commented on index.html
> +            <span class="tooltip"></span>
Понял, исправил