Проверка проекта
htmlacademy-htmlcss/825295-sedona-36 pull request #9
Opened 2023-03-06 09:44 UTC by aleksaandr

2023-03-09 10:19 UTC, Dima-Dim requested changes

2023-03-09 10:19 UTC, Dima-Dim commented on catalog.html
> +              <span class="visually-hidden">Первая страница.</span>
Спорная штука.

2023-03-09 10:19 UTC, Dima-Dim commented on catalog.html
>          <ul class="social-list">
Приишёл к выводу что всё есть списки? :) Не нужно так делать.

2023-03-09 10:19 UTC, Dima-Dim commented on styles/styles.css
> +input[type="number"]::-webkit-outer-spin-button,
Может попасть под критерий с глобальными тегами, ведь тут по сути переопределение для всех инпутов с типом число.

2023-03-09 14:03 UTC, aleksaandr commented on catalog.html
> +              <span class="visually-hidden">Первая страница.</span>
> Спорная штука.

Почему? Со скринридером пользователям будет понятнее "первая страница", чем "1".

2023-03-09 14:06 UTC, aleksaandr commented on styles/styles.css
> +input[type="number"]::-webkit-outer-spin-button,
> Может попасть под критерий с глобальными тегами, ведь тут по сути переопределение для всех инпутов с типом число.

Исправил

2023-03-09 14:10 UTC, aleksaandr commented on catalog.html
>          <ul class="social-list">
А почему не положить всё в 1 список? Это же всё типо социальные вещи, ссылки, которые ведут к одному ресурсу.

2023-03-09 15:01 UTC, aleksaandr commented on catalog.html
>          <ul class="social-list">
Разве что телефон хочется вытащить, сложно

2023-03-11 12:56 UTC, Dima-Dim commented on catalog.html
>          <ul class="social-list">
Если так думать, то всю страницу можно списком разметить, ведь это всё про седону :)

2023-03-11 12:56 UTC, merged

2023-03-11 13:12 UTC, aleksaandr commented on catalog.html
>          <ul class="social-list">
Почитаю про списки